cabal-version:       >=1.10

name:                reva 
version:             0.1.1.2
synopsis:            A toy functional language based on Haskell.
-- description:
-- bug-reports:
license:               GPL-3
license-file:          LICENSE
author:                Henry Wandover
maintainer:            henrywandover@gmail.com
-- copyright:             GPL-3
category:              Programming Languages
build-type:            Simple
extra-source-files:    README.md, CHANGELOG.md

library
  exposed-modules:     Reva 
  other-modules:       Reva.Grammar, Reva.Lexer, Reva.TypeChecker, Reva.Interpreter, Reva.Util
  hs-source-dirs:      core/lib-reva/
  include-dirs:        include
  c-sources:           c-src/reva-curses.c
  build-depends:       base, filepath, array, mtl
  default-language:    Haskell2010

executable reva
  main-is:             Main.hs
  build-depends:       base, filepath, array, reva 
  hs-source-dirs:      app
  default-language:    Haskell2010
  build-tool-depends:  happy:happy >= 1.20 && < 1.21

executable revai
  main-is:             Interactive.hs
  build-depends:       base, filepath, haskeline, array, reva 
  hs-source-dirs:      app
  default-language:    Haskell2010

--test-suite tests
--   type:               exitcode-stdio-1.0
--   main-is:            BasicTest.hs
--   hs-source-dirs:     tests
--   build-depends:      GHUT, base, HUnit
--   default-language:   Haskell2010
