name: Build hasktan on MacOS

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Haskell toolchain
      uses: haskell-actions/setup@v2
      with:
        ghc-version: 'latest'
        cabal-version: 'latest'
    - run: cabal update
      
    - name: Install Alex & Happy
      run: cabal install alex happy

    - name: Install GNU readline
      run: |
           brew install readline
           export LIBRARY_PATH=/usr/local/opt/readline/lib:$LIBRARY_PATH
           export C_INCLUDE_PATH=/usr/local/opt/readline/include:$C_INCLUDE_PATH
           export LD_LIBRARY_PATH=/usr/local/opt/readline/lib:$LD_LIBRARY_PATH
           
           brew switch readline 8.0.1
           cd /usr/local/opt/readline/lib
           ln -s libreadline.8.dylib libreadline.7.dylib

    - name: Install readline
      run: cabal install --lib readline -v


    - name: Install dependencies (lab5)
      run: make

    - name: Run check (lab5)
      run: make test
