name: Makefile CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Haskell toolchain
      uses: haskell-actions/setup@v2
      with:
        ghc-version: 'latest'
        cabal-version: 'latest'
    - run: cabal update
      
    - name: Install Alex & Happy
      run: cabal install alex happy

    - run: brew install readline \
           export LDFLAGS="-L/usr/local/opt/readline/lib" \
           export CFLAGS="-I/usr/local/opt/readline/include"

    - name: Install readline
      run: cabal install readline \ 
          --extra-include-dirs=/usr/local/opt/readline/include \ 
          --extra-lib-dirs=/usr/local/opt/readline/lib

    - name: Install dependencies (lab5)
      run: make

    - name: Run check (lab5)
      run: make test
