name: Makefile CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: chmod +x configure.sh
        ./configure.sh

    - name: Install dependencies (lab5)
      run: cd labs/lab5/
        make

    - name: Run check (lab5)
      run: cd labs/lab5/
        make test
