name: Build hasktan on MacOS

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Haskell toolchain
      uses: haskell-actions/setup@v2
      with:
        ghc-version: 'latest'
        cabal-version: 'latest'
    - run: cabal update
      
    - name: Install Alex & Happy
      run: cabal install alex happy

    - name: Install GNU readline
      run: |
           brew install with-readline

    - name: Install readline
      run: cabal install --lib readline -v


    - name: Install dependencies (lab5)
      run: make

    - name: Run check (lab5)
      run: make test
